import QtQuick 2.0
import QtQuick.Controls 1.0
import QtQuick.Layouts 1.0
import QtQuick.Controls.Styles 1.0
import QtGraphicalEffects 1.0
import MasterCatalogModel 1.0
import TranquilizerHandler 1.0
import UIContextModel 1.0
import "../Global.js" as Global
import "../controls" as Controls

Rectangle {
    id : buttonB
    y : 0
    height : parent.height
    width :colContainer.width
    color : uicontext.paleColor

  

    DropShadow {
        id: butShadow
       // z: colContainer.z + 1
        anchors.fill: source
        cached: true
        horizontalOffset: 4
        radius: 6
        samples: 12
        color: "#80000000"
        smooth: true
        opacity: 0.7
        source: colContainer
    }

    Item {
        id : colContainer
        width : butColumn.width + 7
        height : parent.height
        Column {
            id : butColumn
            width : 70
            height : 900 // Math.min(1100,parent.height)
            property bool initial : true
            z: buttonB.z + 1
			property var butheight : (height - aArea.height) / (children.length - 1)

			Rectangle {
				id : aArea
				width : parent.width
				height : 70
				color : uicontext.middleColor
				Image {
					width : 54
					height : 27
					source : "../images/ilwis_logo_txt.png"
					x : 5
					y : 2
				}
			}

            WorkBenchButton{
                id : nav
                objectName : "workbench_navbutton_mainui"
                iconname: butColumn.initial ? "locator_white.svg" : (checked ? "locator_green.svg" : "locator_white.svg")
                label: qsTr("Locator")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(nav)
                    transitionInfoPane("navigator","toggle")
                }

                Controls.ToolTip {
                    target: nav
                    text: qsTr("Access to navigation over data sources. Bookmark creation")
                }
            }

            WorkBenchButton{
                id : oper
                iconname : checked ? "operations_green.svg" : "operations_white.svg"
                label: qsTr("Operations")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(oper)
                    transitionInfoPane("operationselection","toggle")
                }

                Controls.ToolTip {
                    target: oper
                    text: qsTr("Browsing and executing data operations")
                }

            }
            WorkBenchButton{
                id : prop
                iconname : checked ? "metadata_green.svg" : "metadata_white.svg"
                label: qsTr("Metadata")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(prop)
                    transitionInfoPane("objectproperties","toggle")
                }

                Controls.ToolTip {
                    target: prop
                    text: qsTr("Acces to metadata of IlwisObjects selected in the active catalog")
                }

            }
            WorkBenchButton{
                id : create
                iconname : checked ? "create_green.svg" : "create_white.svg"
                label: qsTr("Create")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(create)
                    transitionInfoPane("objectcreation","toggle")
                }

                Controls.ToolTip {
                    target: create
                    text: qsTr("Creation of IlwisObjects")
                }
            }
            WorkBenchButton{
                id : errors
                iconname : checked ? "message_green.svg" : "message_white.svg"
                label: qsTr("Messages")
				height : butColumn.butheight
				bgcolor :  messagehandler.color != "#008000" ?  messagehandler.color : uicontext.middleColor
                function mouseClicked() {
					console.debug(messagehandler.color, uicontext.middleColor)
                    toggle(errors)
                    transitionInfoPane("messages","toggle")
                }

                Controls.ToolTip {
                    target: errors
                    text: qsTr("Messages generated by the system including warnings and errors")
                }
            }
            WorkBenchButton{
                id : progress
                ProgressBar {
                    anchors.top: progress.top
                    anchors.topMargin: 5
                    width : parent.width - 10
                    x : 5
                    height : 12
                    maximumValue: 100
                    minimumValue: 0
                    value : tranquilizerHandler.aggregateValue
                    opacity: (value > 0) ? 0.55 : 0

                    style: ProgressBarStyle {
                        background: Rectangle {
                            radius: 2
                            color: "grey"
                            border.color: "gray"
                            border.width: 1
                        }
                        progress: Rectangle {
                            color: uicontext.lightColor
                            border.color: uicontext.darkestColor
                        }
                    }

                }

                iconname : checked ? "progress_green.svg" : "progress_white.svg"
                label: qsTr("Progress")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(progress)
                    transitionInfoPane("tranquilizers","toggle")
                }

                Controls.ToolTip {
                    target: progress
                    text: qsTr("Progress of currently running operations and actions")
                }

            }
            WorkBenchButton{
                id : preferences
                iconname : checked ? "settings_green.svg" : "settings_white.svg"
                label: qsTr("Settings")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(preferences)
                    transitionInfoPane("preferences","toggle")
                }

                Controls.ToolTip {
                    target: preferences
                    text: qsTr("User defined settings for Ilwis 4")
                }

            }
            WorkBenchButton{
                id : info
                iconname : checked ? "info_green.svg" : "info_white.svg"
                label: qsTr("Info")
				height : butColumn.butheight
                function mouseClicked() {
                    toggle(info)
                    transitionInfoPane("info","toggle")
                }

                Controls.ToolTip {
                    target: info
                    text: qsTr("Information on Ilwis 4")
                }
            }

        }
        Rectangle {
            anchors.top : butColumn.bottom
            anchors.bottom: colContainer.bottom
            width : parent.width - 7
            color : uicontext.middleColor
        }
    }

    states: [
        State { name: "visible"

            PropertyChanges {
                target: buttonB
                width : 70
            }
        },
        State {
            name : "invisible"
            PropertyChanges {
                target: buttonB
                width : 0
            }
        }

    ]
    transitions: [
        Transition {
            NumberAnimation { properties: "width"; duration : 300 ; easing.type: Easing.InOutCubic }
        }
    ]

  function setButtonStatus(buttonname, status) {
        if ( status === "toggle"){
            toggle(buttonname,status)
            return
        }

        prop.checked = nav.checked = oper.checked = errors.checked = progress.checked = create.checked = preferences.checked = false
        if ( buttonname === "navigator"){
            nav.checked = status === "on"
        }
        if ( buttonname === "operationselection")
            oper.checked = status === "on"
        if ( buttonname === "objectproperties")
            prop.checked = status === "on"
        if ( buttonname === "messages")
            errors.checked = status === "on"
        if ( buttonname === "tranquilizer")
            progress.checked = status === "on"
        if ( buttonname === "objectcreation")
            create.checked = status === "on"
        if ( buttonname === "info")
            info.checked = status === "on"
        if ( buttonname === "preferences")
            preferences.checked = status === "on"

    }
    function toggle(button, visibility) {
        var currentValue = button.checked
        prop.checked = nav.checked = oper.checked = errors.checked = progress.checked = create.checked = preferences.checked = false
        button.checked = !currentValue
        butColumn.initial = false
    }
}
