name: Build ilwispy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.8', '3.10']

    steps:
    - uses: actions/checkout@v4
    - name: install python
      uses: actions/setup-python@v5
      with:
          # Semantic version range syntax or exact version of a Python version
          python-version: ${{ matrix.python-version }}
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
    - name: install dependencies
      run: |
           sudo apt-get install build-essential
           sudo apt-get install qt5-qmake
           sudo apt-get install qtbase5-dev
           sudo apt-get install python3-dev
           sudo apt-get install libquazip5-dev
           sudo apt-get install libboost-dev
           sudo apt-get install libgdal-dev
           sudo apt-get install libgsl-dev
           sudo apt-get install libeigen3-dev
           sudo apt-get install libnetcdf-c++4-dev
           sudo apt-get install swig3.0
    - name: install python packages
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install wheel setuptools
    - name: patch
      run: |
           python3 patch_pythonapi_linux.py
           ln -s /usr/include/quazip5/ ilwis4connector/quazip
    - name: configure
      run: |
           qmake -o Makefile.core core.pro
           qmake -o Makefile.baseoperations baseoperations.pro
           qmake -o Makefile.featureoperations featureoperations.pro
           qmake -o Makefile.gdalconnector gdalconnector.pro
           qmake -o Makefile.hydroflow hydroflow.pro
           qmake -o Makefile.ilwis3connector ilwis3connector.pro
           qmake -o Makefile.ilwis4connector ilwis4connector.pro
           qmake -o Makefile.ilwisscript ilwisscript.pro
           qmake -o Makefile.internalconnector internalconnector.pro
           qmake -o Makefile.netcdfconnector netcdfconnector.pro
           qmake -o Makefile.opencv opencv.pro
           qmake -o Makefile.projectionimplproj4 projectionimplproj4.pro
           qmake -o Makefile.pythonapi pythonapi.pro
           qmake -o Makefile.rasteroperations rasteroperations.pro
           qmake -o Makefile.streamconnector streamconnector.pro
           qmake -o Makefile ilwisobjects.pro
    - name: make
      run: make -f Makefile
