name: Testing the installation of Python

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: install tools
      run: |
           c:
           cd \
           choco install -y python38 --params "/InstallDir:C:\Python38" --force --apply-package-parameters-to-dependencies
           choco install -y python39 --params "/InstallDir:C:\Python39" --force --apply-package-parameters-to-dependencies
           dir c:\
           dir c:\python39
           dir c:\python38
           c:\python38\python.exe -m pip install --upgrade pip
           c:\python38\python.exe -m pip install wheel
           c:\python39\python.exe -m pip install --upgrade pip
           c:\python39\python.exe -m pip install wheel
