name: Testing the installation of Python

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: install tools
      run: |
           c:
           cd \
           mkdir Python
           choco install -y python38 --params "/InstallDir:C:\Python\Python38" --force --apply-package-parameters-to-dependencies
           choco install -y python39 --params "/InstallDir:C:\Python\Python39" --force --apply-package-parameters-to-dependencies
           choco install -y python38 --params "/InstallDir:C:\Python38" --force --apply-package-parameters-to-dependencies
           choco install -y python39 --params "/InstallDir:C:\Python39" --force --apply-package-parameters-to-dependencies
           dir c:\
           dir c:\Python\python39
           dir c:\Python\python38
